# Generated by Django 5.2.5 on 2025-08-25 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=500, unique=True, verbose_name='Nombre del proyecto')),
                ('proveedor', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=500, unique=True, verbose_name='Nombre del proveedor')),
                ('codigo_acceso', models.CharField(help_text='Código único para acceder al proyecto', max_length=100, unique=True, verbose_name='Código de acceso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('completado', 'Completado')], default='activo', help_text='Estado actual del proyecto', max_length=20, verbose_name='Estado')),
                ('tipo_envio', models.CharField(choices=[('automatico', 'Automatico'), ('programado', 'Programado'), ('manual', 'Manual')], default='inmediato', help_text='Modalidad de envío de mensajes', max_length=20, verbose_name='Tipo de envío')),
                ('tipo_alerta', models.CharField(choices=[('redes', 'Redes'), ('medios', 'Medios')], default='medios', help_text='Tipo de notificación a enviar', max_length=20, verbose_name='Tipo de alerta')),
                ('formato_mensaje', models.CharField(choices=[('uno a uno', 'Uno a uno'), ('muchos en uno', 'Muchos en uno')], default='uno a uno', help_text='Formato mensaje a enviar', max_length=20, verbose_name='Formato mensaje')),
                ('keywords', models.TextField(blank=True, help_text='Palabras clave separadas por comas para filtrar mensajes', null=True, verbose_name='Palabras clave')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nombre'], name='proyectos_p_nombre_a27968_idx'), models.Index(fields=['codigo_acceso'], name='proyectos_p_codigo__91a309_idx'), models.Index(fields=['estado'], name='proyectos_p_estado_fd8518_idx')],
            },
        ),
    ]
