# Generated by Django 5.2.5 on 2025-09-02 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=500, verbose_name='Nombre del proyecto')),
                ('proveedor', models.CharField(help_text='Nombre descriptivo del proveedor', max_length=500, verbose_name='Nombre del proveedor')),
                ('codigo_acceso', models.CharField(help_text='Código único para acceder al proyecto', max_length=100, verbose_name='Código de acceso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('completado', 'Completado')], default='activo', help_text='Estado actual del proyecto', max_length=20, verbose_name='Estado')),
                ('tipo_envio', models.CharField(choices=[('automatico', 'Automatico'), ('programado', 'Programado'), ('manual', 'Manual')], default='manual', help_text='Modalidad de envío de mensajes', max_length=20, verbose_name='Tipo de envío')),
                ('tipo_alerta', models.CharField(choices=[('redes', 'Redes'), ('medios', 'Medios')], default='medios', help_text='Tipo de notificación a enviar', max_length=20, verbose_name='Tipo de alerta')),
                ('formato_mensaje', models.CharField(choices=[('uno a uno', 'Uno a uno'), ('muchos en uno', 'Muchos en uno')], default='uno a uno', help_text='Formato mensaje a enviar', max_length=20, verbose_name='Formato mensaje')),
                ('keywords', models.TextField(blank=True, help_text='Palabras clave separadas por comas para filtrar mensajes', null=True, verbose_name='Palabras clave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'indexes': [models.Index(fields=['nombre'], name='proyectos_p_nombre_a27968_idx'), models.Index(fields=['codigo_acceso'], name='proyectos_p_codigo__91a309_idx'), models.Index(fields=['estado'], name='proyectos_p_estado_fd8518_idx')],
            },
        ),
    ]
