# Generated by Django 5.2.5 on 2025-08-25 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_acceso',
            field=models.CharField(help_text='Código único para acceder al proyecto', max_length=100, verbose_name='Código de acceso'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Fecha de modificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proveedor',
            field=models.CharField(help_text='Nombre descriptivo del proveedor', max_length=500, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_envio',
            field=models.CharField(choices=[('automatico', 'Automatico'), ('programado', 'Programado'), ('manual', 'Manual')], default='manual', help_text='Modalidad de envío de mensajes', max_length=20, verbose_name='Tipo de envío'),
        ),
    ]
