# Generated by Django 5.2.5 on 2025-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_codigo_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del proyecto', max_length=500, verbose_name='Nombre del proyecto'),
        ),
    ]
