# Generated by Django 5.2.5 on 2025-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_created_by_proyecto_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nombre_grupo',
            field=models.CharField(blank=True, help_text='Nombre del grupo', max_length=500, null=True, verbose_name='Nombre del nombre_grupo'),
        ),
    ]
