# Generated by Django 4.2.7 on 2025-09-22 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proyectos", "0003_proyecto_nombre_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_creado_por",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modificado_por",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
    ]
