# Generated by Django 4.2.7 on 2025-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_proyecto_created_by_alter_proyecto_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="criterios_aceptacion",
            field=models.TextField(
                blank=True,
                help_text="Palabras clave separadas por comas para aceptar mensajes de ingestión",
                null=True,
                verbose_name="Criterios de aceptación",
            ),
        ),
    ]
