# Generated by Django 5.2.5 on 2026-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_criterios_aceptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del proveedor', max_length=500, null=True, verbose_name='Nombre del proveedor'),
        ),
    ]
