# Generated by Django 5.2.5 on 2025-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='estado_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='estado_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
