# Generated by Django 5.2.5 on 2025-09-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleenvio',
            name='fin_envio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='detalleenvio',
            name='inicio_envio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldetalleenvio',
            name='fin_envio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldetalleenvio',
            name='inicio_envio',
            field=models.DateTimeField(null=True),
        ),
    ]
