# Generated by Django 5.2.5 on 2025-09-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_detalleenvio_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redes',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
    ]
