# Generated by Django 5.2.5 on 2025-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_templateconfig_templatecampoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateconfig',
            name='config_campos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
