# Generated by Django 5.2.5 on 2025-09-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_templateconfig_config_campos'),
        ('proyectos', '0002_proyecto_created_by_proyecto_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_envio', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.proyecto'),
        ),
    ]
