# Generated by Django 5.2.5 on 2025-09-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_detalleenvio_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='estado_revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='estado_revisado',
            field=models.BooleanField(default=False),
        ),
    ]
