# Generated by Django 4.2.7 on 2025-09-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_detalleenvio_estado_revisado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="autor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="titulo",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="title"
            ),
        ),
    ]
