# Generated by Django 5.2.5 on 2025-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_articulo_created_by_alter_articulo_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='redes',
            name='autor',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
