# Generated by Django 5.2.5 on 2025-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_articulo_autor_alter_redes_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='engagement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
