# Generated by Django 5.2.5 on 2025-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_articulo_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fuente',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Fuente/Medio'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo_medio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Medio'),
        ),
    ]
