# Generated by Django 5.2.5 on 2026-01-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_articulo_fuente_articulo_tipo_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='redes',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
