# Generated by Django 5.2.5 on 2026-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_articulo_ubicacion_redes_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecampoconfig',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
