# Generated by Django 4.2.7 on 2026-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_templatecampoconfig_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='estado_pipeline',
            field=models.CharField(choices=[('manual', 'Manual / legacy'), ('pendiente_ia', 'Pendiente IA'), ('clasificando', 'Clasificando'), ('enriqueciendo', 'Enriqueciendo'), ('auto_aprobada', 'Auto-aprobada'), ('cola_excepciones', 'Cola de excepciones'), ('aprobada_humana', 'Aprobada por humano'), ('descartada_ia', 'Descartada por IA'), ('descartada_humana', 'Descartada por humano'), ('enviada', 'Enviada'), ('error_envio', 'Error de envío')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleenvio',
            name='intentos_ia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleenvio',
            name='proveedor_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='estado_pipeline',
            field=models.CharField(choices=[('manual', 'Manual / legacy'), ('pendiente_ia', 'Pendiente IA'), ('clasificando', 'Clasificando'), ('enriqueciendo', 'Enriqueciendo'), ('auto_aprobada', 'Auto-aprobada'), ('cola_excepciones', 'Cola de excepciones'), ('aprobada_humana', 'Aprobada por humano'), ('descartada_ia', 'Descartada por IA'), ('descartada_humana', 'Descartada por humano'), ('enviada', 'Enviada'), ('error_envio', 'Error de envío')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='intentos_ia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldetalleenvio',
            name='proveedor_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
